// tb_mate_pv.sv — bit-exact check of mate_pv vs the ACU MAC-array reference.
// Streams each golden row (K tokens of a_data + packed v_data) through the DUT and
// compares the N int32 results against matmul_int8 (generated by gen_mate_pv_vectors.py).
`timescale 1ns/1ps
module tb_mate_pv;
    localparam integer N     = 8;
    localparam integer AW    = 8;
    localparam integer VW    = 8;
    localparam integer ACC_W = 32;

    reg clk = 0, rst_n = 0;
    always #5 clk = ~clk;

    reg                     s_valid;
    reg  signed [AW-1:0]    a_data;
    reg         [N*VW-1:0]  v_data;
    reg                     s_last;
    wire                    c_valid;
    wire signed [N*ACC_W-1:0] c_data;

    mate_pv #(.N(N), .AW(AW), .VW(VW), .ACC_W(ACC_W)) dut (
        .clk(clk), .rst_n(rst_n),
        .s_valid(s_valid), .a_data(a_data), .v_data(v_data), .s_last(s_last),
        .c_valid(c_valid), .c_data(c_data));

    integer fd, code, Ncheck, ROWS, K, r, t, n;
    integer av, vv, cexp;
    integer rows_pass, errors;
    reg [N*ACC_W-1:0] gold;   // packed expected results for the row

    initial begin
        fd = $fopen("mate_pv_vectors.txt", "r");
        if (fd == 0) begin $display("FATAL: mate_pv_vectors.txt missing (run gen_mate_pv_vectors.py)"); $finish; end
        code = $fscanf(fd, "%d %d\n", Ncheck, ROWS);
        if (Ncheck !== N) begin $display("FATAL: vector N=%0d != TB N=%0d", Ncheck, N); $finish; end

        s_valid = 0; a_data = 0; v_data = 0; s_last = 0;
        rst_n = 0; repeat (3) @(negedge clk); rst_n = 1; @(negedge clk);

        rows_pass = 0; errors = 0;

        for (r = 0; r < ROWS; r = r + 1) begin
            code = $fscanf(fd, "%d\n", K);
            // stream K tokens — drive ALL inputs together AFTER the negedge so they
            // are stable across the sampling posedge (setting v_data before the edge
            // lets the next token clobber it early: an a[t]·v[t+1] off-by-one).
            for (t = 0; t < K; t = t + 1) begin
                @(negedge clk);
                code = $fscanf(fd, "%d", av);
                a_data = av[AW-1:0];
                for (n = 0; n < N; n = n + 1) begin
                    code = $fscanf(fd, "%d", vv);
                    v_data[n*VW +: VW] = vv[VW-1:0];
                end
                s_valid = 1; s_last = (t == K-1);
            end
            // read expected results
            for (n = 0; n < N; n = n + 1) begin
                code = $fscanf(fd, "%d", cexp);
                gold[n*ACC_W +: ACC_W] = cexp;
            end
            // wait for the c_valid handshake (pipelined: emerges 2 cycles after
            // s_last — the wait makes the TB latency-agnostic)
            @(negedge clk);
            s_valid = 0; s_last = 0;
            begin : wait_cv
                integer w;
                for (w = 0; w < 6 && c_valid !== 1'b1; w = w + 1) @(negedge clk);
            end
            if (c_valid !== 1'b1) begin
                errors = errors + 1;
                $display("  row %0d (K=%0d): c_valid did not pulse", r, K);
            end else begin
                for (n = 0; n < N; n = n + 1) begin
                    if ($signed(c_data[n*ACC_W +: ACC_W]) !== $signed(gold[n*ACC_W +: ACC_W])) begin
                        errors = errors + 1;
                        $display("  row %0d lane %0d: got %0d exp %0d", r, n,
                                 $signed(c_data[n*ACC_W +: ACC_W]), $signed(gold[n*ACC_W +: ACC_W]));
                    end
                end
                if (errors == 0 || 1) rows_pass = rows_pass + ((c_valid===1'b1) ? 1 : 0);
            end
            @(negedge clk);   // gap between rows
        end
        $fclose(fd);

        $display("Tests: %0d  Pass: %0d  Errors: %0d", ROWS, rows_pass, errors);
        if (errors == 0) $display("ALL TESTS PASSED — mate_pv bit-exact vs matmul_int8 (INT32 P.V tile)");
        else             $display("FAILED — %0d mismatches", errors);
        $finish;
    end
endmodule
