// tb_mate_qkt.sv — bit-exact check of mate_qkt vs the Q·Kᵀ decode-scoring golden.
// Streams each golden row (D head-dim channels: an INT8 query code + the L keys'
// d-th channel as fp16) through the DUT and compares the L fp16 scores against the
// sequential-fp32 reference (generated by gen_mate_qkt_vectors.py). Scores compared
// as raw 16-bit fp16 codes — inf (0x7C00/0xFC00) compares exactly.
`timescale 1ns/1ps
module tb_mate_qkt;
    parameter  integer L  = 8;   // number of keys / score lanes (override via -P for L=1, 520)
    localparam integer QW = 8;
    localparam integer FW = 16;

    reg clk = 0, rst_n = 0;
    always #5 clk = ~clk;

    reg                 s_valid;
    reg  signed [QW-1:0] a_data;
    reg  [L*FW-1:0]     k_data;
    reg                 s_last;
    wire                c_valid;
    wire [L*FW-1:0]     c_data;

    mate_qkt #(.N(L), .QW(QW), .FW(FW)) dut (
        .clk(clk), .rst_n(rst_n),
        .s_valid(s_valid), .a_data(a_data), .k_data(k_data), .s_last(s_last),
        .c_valid(c_valid), .c_data(c_data));

    integer fd, code, Lcheck, ROWS, D, r, d, n;
    integer qv, kv, cexp;
    integer rows_pass, errors;
    reg [L*FW-1:0] gold;   // packed expected fp16 scores for the row

    initial begin
        fd = $fopen("mate_qkt_vectors.txt", "r");
        if (fd == 0) begin $display("FATAL: mate_qkt_vectors.txt missing (run gen_mate_qkt_vectors.py)"); $finish; end
        code = $fscanf(fd, "%d %d\n", Lcheck, ROWS);
        if (Lcheck !== L) begin $display("FATAL: vector L=%0d != TB L=%0d", Lcheck, L); $finish; end

        s_valid = 0; a_data = 0; k_data = 0; s_last = 0;
        rst_n = 0; repeat (3) @(negedge clk); rst_n = 1; @(negedge clk);

        rows_pass = 0; errors = 0;

        for (r = 0; r < ROWS; r = r + 1) begin
            code = $fscanf(fd, "%d\n", D);
            // stream D channels — drive ALL inputs together AFTER the negedge so they
            // are stable across the sampling posedge (same discipline as tb_mate_pv).
            for (d = 0; d < D; d = d + 1) begin
                @(negedge clk);
                code = $fscanf(fd, "%d", qv);
                a_data = qv[QW-1:0];
                for (n = 0; n < L; n = n + 1) begin
                    code = $fscanf(fd, "%d", kv);
                    k_data[n*FW +: FW] = kv[FW-1:0];
                end
                s_valid = 1; s_last = (d == D-1);
            end
            // read expected fp16 scores
            for (n = 0; n < L; n = n + 1) begin
                code = $fscanf(fd, "%d", cexp);
                gold[n*FW +: FW] = cexp[FW-1:0];
            end
            // wait for the c_valid handshake (pipelined: emerges 2 cycles after s_last)
            @(negedge clk);
            s_valid = 0; s_last = 0;
            begin : wait_cv
                integer w;
                for (w = 0; w < 6 && c_valid !== 1'b1; w = w + 1) @(negedge clk);
            end
            if (c_valid !== 1'b1) begin
                errors = errors + 1;
                $display("  row %0d (D=%0d): c_valid did not pulse", r, D);
            end else begin
                for (n = 0; n < L; n = n + 1) begin
                    if (c_data[n*FW +: FW] !== gold[n*FW +: FW]) begin
                        errors = errors + 1;
                        $display("  row %0d key %0d: got %04x exp %04x", r, n,
                                 c_data[n*FW +: FW], gold[n*FW +: FW]);
                    end
                end
                rows_pass = rows_pass + ((c_valid === 1'b1) ? 1 : 0);
            end
            @(negedge clk);   // gap between rows
        end
        $fclose(fd);

        $display("Tests: %0d  Pass: %0d  Errors: %0d", ROWS, rows_pass, errors);
        if (errors == 0) $display("ALL TESTS PASSED — mate_qkt bit-exact vs Q.Kt golden (fp32-accumulate, round-to-fp16)");
        else             $display("FAILED — %0d mismatches", errors);
        $finish;
    end
endmodule
